Даны значения величины заработной платы заемщиков банка (zp) и значения их поведенческого кредитного скоринга (ks): zp = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110], ks = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832]. Используя математические операции, посчитать коэффициенты линейной регрессии, приняв за X заработную плату (то есть, zp - признак), а за y - значения скорингового балла (то есть, ks - целевая переменная). Произвести расчет как с использованием intercept, так и без

In [11]:
import numpy as np


In [12]:
X = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
X

array([ 35,  45, 190, 200,  40,  70,  54, 150, 120, 110])

In [13]:
y = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])
y

array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])

In [14]:
n=len(X)
n

10

In [14]:
b= (np.mean(X*y)-np.mean(X)*np.mean(y))/(np.mean(X**2)-(np.mean(X)**2)) #угол наклона
b

2.620538882402765

In [16]:
a=np.mean(y)-b*np.mean(X) #интерсепт
a

444.1773573243596

In [15]:
X=X.reshape((10,1)) #матричный метод
X

array([[ 35],
       [ 45],
       [190],
       [200],
       [ 40],
       [ 70],
       [ 54],
       [150],
       [120],
       [110]])

In [16]:
y =y.reshape((10,1))
y

array([[401],
       [574],
       [874],
       [919],
       [459],
       [739],
       [653],
       [902],
       [746],
       [832]])

In [17]:
B= np.dot(np.linalg.inv(np.dot(X.T,X)),X.T @ y) #без интерсепта
B

array([[5.88982042]])

In [18]:
X= np.hstack([np.ones((10,1)), X])
X

array([[  1.,  35.],
       [  1.,  45.],
       [  1., 190.],
       [  1., 200.],
       [  1.,  40.],
       [  1.,  70.],
       [  1.,  54.],
       [  1., 150.],
       [  1., 120.],
       [  1., 110.]])

In [19]:
B= np.dot(np.linalg.inv(np.dot(X.T,X)),X.T @ y) #с интерсептом [интерсепт, угол наклона]
B

array([[444.17735732],
       [  2.62053888]])